DEBUG = True
SESSION_LIMIT = 5
COOKIE_DURATION = 30

MIN_USERNAME_LENGTH = 3
MAX_USERNAME_LENGTH  = 15

MIN_PASSWORD_LENGTH = 5
MAX_PASSWORD_LENGTH = 200

MIN_DISPLAY_NAME_LENGTH = 2
MAX_DISPLAY_NAME_LENGTH = 25
