import Inferno from "inferno";
export default function Main() {
  // God Bless America.
  console.log("HELLO, I AM THE MAIN. MASTER BRAIN, BRUCE WAYNE WITH THE PRIVATE AIRPLANE");
  console.log("MIX THE MIC, DOCTOR GOTHAM DROPS BARS JUST TO SATISFY HIS APPETITE");
  console.log("NO CREW SAFE FROM THE ALPHA CAT, THE SIX STRINGED BAT, FISTS SO TIGHT THAT THEY CALL HIM THE ALCATRAZ");
  console.log("THE CAPED CRUSADER WITH THE THREE STEP CURE FOR HATERS CALLED THE SEE YOU LATER");
  console.log("STEP TO THE BRUCE AND HE'LL BREAK THE BEAT, MESS YOUR FLOW UP IRREPLACEABLY, THE HALF CRACKED MAN BAT WITH THE NET WORTH OF THE NASDAQ");
  console.log("STEP OUT THE BATMOBILE, NEW HAS-BEENS, RIP THE TRACK IN HALF AND WREAK HAVOC");
  console.log("THROW THE ROPE, TIE THE TASSEL TO THE THROAT, AND TRIPLE TRIP THE TRIPS TO TOTAL THIS TO TRAGIC");
}

Main();
